language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - chmod 0600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - ./deploy.sh
